version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    environment:
      - NODE_ENV=development
    ports:
      - "8000:4321"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped